server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tracking_alumni
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-to-a-secure-value}
    expiration-seconds: 86400

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
